/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Alertas: () => import('#controllers/alertas_controller'),
  Bodega: () => import('#controllers/bodega_controller'),
  Categorias: () => import('#controllers/categorias_controller'),
  ClasificacionesElemento: () => import('#controllers/clasificaciones_elemento_controller'),
  CodigosEstandar: () => import('#controllers/codigos_estandar_controller'),
  Elementos: () => import('#controllers/elementos_controller'),
  Entregas: () => import('#controllers/entregas_controller'),
  Items: () => import('#controllers/items_controller'),
  Modules: () => import('#controllers/modules_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notificaciones: () => import('#controllers/notificaciones_controller'),
  Obras: () => import('#controllers/obras_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Roles: () => import('#controllers/roles_controller'),
  SolicitudEquipo: () => import('#controllers/solicitud_equipo_controller'),
  SolicitudMaterial: () => import('#controllers/solicitud_material_controller'),
  Solicitudes: () => import('#controllers/solicitudes_controller'),
  Stand: () => import('#controllers/stand_controller'),
  SubBodegas: () => import('#controllers/sub_bodegas_controller'),
  Subcategorias: () => import('#controllers/subcategorias_controller'),
  UnidadesMedida: () => import('#controllers/unidades_medida_controller'),
  Users: () => import('#controllers/users_controller'),
  UsosPresupuestales: () => import('#controllers/usos_presupuestales_controller'),
}
