/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Bodega: () => import('#controllers/bodega_controller'),
  Categorias: () => import('#controllers/categorias_controller'),
  Modules: () => import('#controllers/modules_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Stand: () => import('#controllers/stand_controller'),
  Subcategorias: () => import('#controllers/subcategorias_controller'),
  Users: () => import('#controllers/users_controller'),
}
